#! /bin/bash

# Keyboard Shortcuts
sxhkd &

# Wallpaper
wal -i /home/troy/Pictures/Wallpapers/geo3.jpg 

# Transparency
pkill compton
compton &

#bspc monitor eDP-1 -n 0 -d I II III IV V VI VII VIII IX X
#bspc monitor HDMI-1 -n 1 -d I II III IV V VI VII VIII IX X

HDMI=$(xrandr -q | grep HDMI-1 | awk '{print $2}')
DVI=$(xrandr -q | grep DVI-I-1-1 | awk '{print $2}')

if [ "$DVI" == "connected" ] && [ "$HDMI" == "connected" ]; then
	bspc monitor DVI-I-1-1 -d 1 2
	bspc monitor eDP-1 -d 3 4 5
	bspc monitor DVI-I-2-2 -d 6 7 8
        bspc monitor HDMI-1 -d 9 10
elif [ "$DVI" == "connected" ]; then
	bspc monitor DVI-I-1-1 -d 1 2 3
	bspc monitor eDP-1 -d 4 5 6
	bspc monitor DVI-I-2-2 -d 7 8 9 10
elif [ "$HDMI" == "connected" ]; then
	bspc monitor HDMI-1 -d 6 7 8 9 10
	bspc monitor eDP-1 -d 1 2 3 4 5
else
	bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10
fi


# Polybar
/home/troy/.config/polybar/launch.sh & 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
bspc config remove_unplugged_monitors true

bspc config single_monocle true 
